sequenceDiagram
    participant Navegador
    participant Servidor

    Navegador->>Servidor: GET /spa
    activate Servidor
    Servidor-->>Navegador: documento HTML
    deactivate Servidor

    Navegador->>Servidor: GET /main.css
    activate Servidor
    Servidor-->>Navegador: archivo CSS
    deactivate Servidor

    Navegador->>Servidor: GET /spa.js
    activate Servidor
    Servidor-->>Navegador: archivo JavaScript (spa.js)
    deactivate Servidor

    Note right of Navegador: Navegador ejecuta código spa.js
    Navegador->>Servidor: GET /data.json
    activate Servidor
    Servidor-->>Navegador: JSON con notas
    deactivate Servidor

    Note right of Navegador: SPA renderiza notas con JS (sin recargar página)